branches:
  only:
    - master

init:
  - ps: $PSVersionTable

build_script:
  - ps: ./bootstrap.ps1

test_script:
  - ps: bundle exec rake
  - ps: chef exec inspec exec test/integration/**/*.rb --format documentation
