branches:
  only:
    - master

init:
  - ps: $PSVersionTable

build_script:
  - ps: ./bootstrap.ps1

test_script:
  - ps: chef exec bundle install
  - ps: chef exec bundle exec rake
  - ps: chef exec inspec exec test/integration/**/*.rb --format documentation
  - ps: $env:PASSWORD = ''; workup --dry-run
