branches:
  only:
    - master

init:
  - ps: $PSVersionTable

build_script:
  - ps: . { (New-Object System.Net.WebClient).DownloadString('https://omnitruck.chef.io/install.sh') } | iex; install -project 'chefdk' -version '0.17.17'
  - ps: chef exec bundle install
  - ps: chef exec bundle exec rake
  - ps: chef gem build ./workup.gemspec
  - ps: chef gem install ./workup-0.1.0.gem --bindir '/usr/local/bin'
  - ps: mkdir ~/.workup
  - ps: cp ./files/Policyfile.rb ~/.workup/Policyfile.rb
  - ps: cp ./files/client.rb ~/.workup/client.rb
  - ps: $env:PASSWORD = ''; workup
