sudo: required
language: ruby
rvm:
  - 2.2.4

branches:
  only:
    - master

script:
  - bundle exec rake
  - sudo ./bootstrap.sh
  - chef exec inspec exec test/integration/**/*.rb --format documentation
