os:
  - linux
  - osx

sudo: required

branches:
  only:
    - master

script:
  - sudo ./bootstrap.sh
  - chef exec inspec exec test/integration/**/*.rb --format documentation
  - chef exec bundle install
  - chef exec bundle exec rake
  - cat /usr/local/bin/workup
  - cat /home/travis/.rvm/gems/ruby-2.2.5/bin/workup
  - which workup
  - PASSWORD='' workup --dry-run
