os:
  - linux
  - osx

language: ruby
rvm:
  - 2.2.3

sudo: required

branches:
  only:
    - master

before_install:
  - gem update bundler

gemfile: omnibus/Gemfile

script:
  - pushd omnibus
  - bundle exec omnibus build workup
