os:
  - linux
  - osx

language: ruby
rvm:
  - 2.3.1

sudo: required

branches:
  only:
    - master

before_install:
  - gem update bundler

install:
  - pushd omnibus
  - bundle install --jobs=3 --retry=3

script:
  - pushd omnibus
  - bundle exec omnibus build workup
