os:
  - linux
  - osx

language: ruby
rvm:
  - 2.2.3

sudo: required

branches:
  only:
    - master

before_install:
  - gem update bundler

install: bundle install --jobs=3 --retry=3 --binstubs

gemfile: omnibus/Gemfile

script:
  - pushd omnibus
  - bundle exec sudo ./bin/omnibus build workup
