driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['..', '/home/vagrant/workup']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.14.89

platforms:
  - name: jhcook/macos-sierra
    driver:
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ['..', '/Users/vagrant/workup', 'type: :nfs, :mount_options => ["nolock,vers=3,udp,noatime"]']
  - name: jhakonen/windows-10-n-pro-en-x86_64
    os_type: windows

suites:
  - name: default
    #run_list: workup_build::default
