driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['..', '/home/vagrant/workup']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.14.89
  log_level: debug

verifier:
  name: inspec
  format: documentation
  inspec_tests:
    - workup_build/test

platforms:
  - name: macos-sierra
    driver:
      box: jhcook/macos-sierra
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ['..', '/Users/vagrant/workup', ':type => :nfs, :mount_options => ["nolock,vers=3,udp,noatime"]']
  - name: windows-10
    driver:
      box: jhakonen/windows-10-n-pro-en-x86_64
      communicator: winrm
      synced_folders:
        - ['..', '/Users/vagrant/workup']

suites:
  - name: default
    run_list: workup_build::default
