driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  synced_folders:
    - ['..', '/vagrant/code/workup']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.14.89

verifier:
  name: inspec
  format: documentation
  inspec_tests:
    - workup_build/test

platforms:
  - name: macos
    driver:
      box: jhcook/macos-sierra
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ['..', '/vagrant/code/workup', ':type => :nfs, :mount_options => ["nolock,vers=3,udp,noatime"]']
  - name: windows-i386
    driver:
      box: mwrock/Windows2016
      synced_folders:
        - ['..', '/Users/vagrant/workup']
    attributes:
      omnibus:
        build_user_group: Administrators

suites:
  - name: default
    run_list: workup_build::default
